import React from "react";
import statement from "../pics/statement.png"

function Statement() {
  return (
    <div className="about">
      <div className="container">
        <div className="row justify-content-center my-5 py-2">
          <img src={statement} alt="img missing" />
        </div>

        <div className="row justify-content-center">
          <h1 style={{ fontSize: 48, fontWeight: 600, color: '#0C71C5' }}>Statement of Faith</h1>

        </div>

        <div className="row align-items-center my-5" style={{ fontSize: 24, fontWeight: 400 }}>
          <p>
            We, the community of believers at Peace and Joy Fellowship Church (PJFC), hold the following Doctrinal Statement as the foundation of our faith and practice:
          </p>

          <p style={{
            fontSize: 24, fontWeight: 700, color: '#0C71C5'
          }}>1.	Scripture:</p>
          <p>We believe in the inerrancy, inspiration, and authority of the Bible as the infallible Word of God. It is our supreme and final authority in all matters of faith and practice.
          </p>

          <p style={{
            fontSize: 24, fontWeight: 700, color: '#0C71C5'
          }}>2.	Trinity: </p> <p>We believe in the one true God, eternally existing in three persons: Father, Son, and Holy Spirit. They are co-equal and co-eternal, and each possesses the same divine nature.
          </p>

          <p style={{
            fontSize: 24, fontWeight: 700, color: '#0C71C5'
          }}>3.	God the Father:</p> <p> We believe in God the Father, who is sovereign, all-knowing, all-powerful, and infinitely loving. He is the creator of the universe and sustainer of all things.
          </p>

          <p style={{
            fontSize: 24, fontWeight: 700, color: '#0C71C5'
          }}>4.	Jesus Christ:</p> <p> We believe in the Lord Jesus Christ, the Son of God, Who became incarnate through the virgin birth, fully God and fully man. He lived a sinless life, died on the cross as
            a substitutionary sacrifice for our sins, and rose from the dead on the third day. He is the only mediator between God and humanity and the only way to salvation.
          </p>

          <p style={{
            fontSize: 24, fontWeight: 700, color: '#0C71C5'
          }}>5.	Holy Spirit:</p> <p> We believe in the Holy Spirit, Who convicts the world of sin, regenerates and indwells believers at the moment of salvation, and empowers them for godly living and service.
            He also gives spiritual gifts to believers to build up the church.
          </p>

          <p style={{
            fontSize: 24, fontWeight: 700, color: '#0C71C5'
          }}>6.	Salvation: </p> <p>We believe that salvation is by grace alone, through faith alone, in Lord Jesus Christ alone. It is not based on human merit or works but is a free gift of God. Those who repent
            of their sins and believe in Lord Jesus Christ as their Saviour and Lord are regenerated by the Holy Spirit, justified, and adopted into the family of God.
          </p>
          <p style={{
            fontSize: 24, fontWeight: 700, color: '#0C71C5'
          }}>7.	Church:</p>  <p>We believe the church is the body of Lord Jesus Christ, composed of all true believers, regardless of denominational affiliation or cultural background. It is called to worship God,
            edify believers, share the message of the good news, and engage in acts of compassion and social justice.
          </p>

          <p style={{
            fontSize: 24, fontWeight: 700, color: '#0C71C5'
          }}>8.	Sacraments:</p>  <p>We believe Baptism and the Lord's Supper are the two sacraments ordained by Lord Jesus Christ for the church.
            Baptism symbolises the believer's identification with Lord Jesus' death, burial, and resurrection and is to be administered to believers by immersion.
            The Lord's Supper is a memorial of Lord Jesus' sacrifice and is to be observed by believers in remembrance of Him.
          </p>

          <p style={{
            fontSize: 24, fontWeight: 700, color: '#0C71C5'
          }}>9.	Second Coming: </p> <p>We believe in the imminent, bodily return of Lord Jesus Christ to earth to judge the living and the dead and to establish
            His eternal kingdom. This is the blessed hope and confident expectation of the church.
          </p>

          <p style={{
            fontSize: 24, fontWeight: 700, color: '#0C71C5'
          }}>10.	Christian Life:</p><p> We believe that Christians are called to live a life of holiness, obedience, and love, empowered by the Holy Spirit.
            They are to be separate from the world and ambassadors of Lord Jesus Christ, proclaiming the gospel and descipling the fellow christians in the way of truth
            and love. They will never indulge in any kind of forced conversions, as it is against the teachings of the Holy Bible.
          </p>

          <p style={{
            fontSize: 24, fontWeight: 700, color: '#0C71C5'
          }}>11.	Final Authority:</p><p> We believe that this Statement of Faith is a summary of the essential doctrines of the Christian faith, as revealed in Scripture.
            It is the final authority in all matters of doctrine and practice for PJFC, and may only be amended by the unanimous consent of the elders.
          </p>
          <p>
            As a church, we hold these truths to be fundamental to our faith, and we commit ourselves to teach, preach, and live in accordance with these biblical
            doctrines, to the glory of God and for the advancement of His kingdom.
          </p>

        </div>
      </div>
    </div >
  );
}

export default Statement;